import dotenv from 'dotenv'
dotenv.config()
import nodemailer from 'nodemailer'
let transporter=nodemailer.createTransport({
    service:'gmail',
    auth:{
        user:process.env.USER,//your email here
        pass:process.env.PASS//your app password here (generated by google)
    }
})
export default  transporter